### ISSUE TITLE
Broken on 10.10.2

### ISSUE THREAD

**Issue by kenvunz** [pstadler/alfred-play#1]
Hi,

This workflow doesn't seem to work on the latest update of Yosemite (10.10.2)

Cheers
Ken

**Comment by pstadler** [comment]
Thanks for reporting. This is a bug in Spotify.app and should be fixed soon.

Discussions:
- http://stackoverflow.com/questions/29039514/applescript-to-tell-spotify-to-play-isnt-working-after-osx-update-to-yosemite
- https://twitter.com/SpotifyPlatform/status/575615437813202944

**Comment by kenvunz** [comment]
there is a workaround in the meantime https://www.unifiedremote.com/tutorials/how-to-get-spotify-version-spotify-101xxx-on-mac-osx. Works for me

**Comment by pstadler** [comment]
Good to know that this works, thanks.

**Comment by pstadler** [comment]
Seems that this has been fixed with one of the recent Spotify releases.
